version: 2.1

jobDefaults: &jobDefaults
  docker:
    - image: node:18-alpine

jobs:
  test:
    <<: *jobDefaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/project/node_modules
      - run: npm i
      - run: npm run test
      - save_cache:
          paths:
            - ~/project/node_modules
          key: v1-{{ checksum "package-lock.json" }}

workflows:
  test:
    jobs:
    - test
